SET NAMES utf8;

CREATE DATABASE IF NOT EXISTS campus CHARSET=utf8;

USE campus;

CREATE TABLE IF NOT EXISTS admin_info(
  a_id INT AUTO_INCREMENT PRIMARY KEY,
  a_names VARCHAR(255) NOT NULL UNIQUE,
  a_pwd VARCHAR(255) NOT NULL
); 

CREATE TABLE IF NOT EXISTS user_info(
  u_id INT AUTO_INCREMENT PRIMARY KEY,
  u_names VARCHAR(255) NOT NULL UNIQUE,
  u_phone VARCHAR(255) NOT NULL UNIQUE,
  u_pwd VARCHAR(255) NOT NULL        
) ;


CREATE TABLE IF NOT EXISTS resume_info(
  re_id INT AUTO_INCREMENT PRIMARY KEY,
  re_names VARCHAR(255) NOT NULL UNIQUE,
  re_phone VARCHAR(255) NOT NULL UNIQUE,
  re_post VARCHAR(255) NOT NULL, 
  re_univ VARCHAR(255) NOT NULL,  
  re_about VARCHAR(255)
);